global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: orientapi
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.194:30090']
    metrics_path: /metrics

  - job_name: node-app
    static_configs:
      - targets: ['10.0.1.194:9100']
    metrics_path: /metrics
