apiVersion: v1
kind: Secret
metadata:
  name: orientapi-jwt
  namespace: orientapi
  labels:
    app.kubernetes.io/name: orientapi
    app.kubernetes.io/part-of: orientops
type: Opaque
stringData:
  jwt_secret: "orientops-jwt-demo-secret-change-in-prod"
  api_username: "demo"
  api_password: "orientops2026"
